export const assetsManifest = {
  bundles: [
    {
      name: "basic",
      assets: {
        numbers: "game/numbers.png",
        font: "game/font.png",
        font2: "game/og-font.png",
        [`8px_numbers`]: "game/8px-numbers.png",
        [`gamer_numbers`]: "game/gamer-numbers.png",
        life: "game/life.png",
        pepper: "game/pepper.png",
        background: "game/background.png",
        small_panel: "game/small-panel.png",
        small_panel_overlay: "game/small-panel-overlay.png",
        score_panel: "game/score-panel.png",
        label_score: "game/label-score.png",
        label_highscore: "game/label-highscore.png",
        light1: "game/light1.png",
        light2: "game/light2.png",
        light1_screen: "game/light1-screen.png",
        light2_screen: "game/light2-screen.png",
        player_pepper: "game/player-pepper.png",
        plate: "game/plate.png",
        plate_with_burger: "game/plate-with-burger.png",
        "flump/atlas": "game/game/atlas0.png",
        "flump/json": "game/game/library.json",
      },
    },
    {
      name: "splash",
      assets: {
        "splash/background": "game/splash/background.png",
        "splash/start": "game/splash/start.png",
        "splash/logo": "game/splash/logo.png",
      },
    },
    {
      name: "player",
      assets: {
        "player/idle": "game/player/idle.png",
        "player/die": "game/player/die.png",
        "player/climb": "game/player/climb.png",
        "player/shoot": "game/player/shoot.png",
        "player/victory": "game/player/victory.png",
        "player/walk": "game/player/walk.png",
      },
    },
  ],
};
